wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1641165939
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 13
      - 16
      4: 3.8.5
      5: 0.12.6
      8:
      - 5
attention_heads:
  desc: null
  value: 4
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
deadlock_reward:
  desc: null
  value: -1000
debug_print:
  desc: null
  value: false
done_reward:
  desc: null
  value: 0
dropout_rate:
  desc: null
  value: 0.8
eps:
  desc: null
  value: 1
eps_decay:
  desc: null
  value: 0.999
evaluation_episodes:
  desc: null
  value: 3
evaluation_interval:
  desc: null
  value: 10
flow:
  desc: null
  value: source_to_target
gat_layers:
  desc: null
  value: 3
grid_mode:
  desc: null
  value: false
height:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.02
learning_rate_decay:
  desc: null
  value: 0.5
learning_rate_decay_policy:
  desc: null
  value: 0.5
load_memory:
  desc: null
  value: false
malfunction_rate:
  desc: null
  value: 0
max_duration:
  desc: null
  value: 50
max_num_cities:
  desc: null
  value: 2
max_rails_between_cities:
  desc: null
  value: 2
max_rails_in_city:
  desc: null
  value: 4
max_steps:
  desc: null
  value: 300
min_duration:
  desc: null
  value: 20
model_name:
  desc: null
  value: ''
model_path:
  desc: null
  value: test_results/
num_agents:
  desc: null
  value: 1
num_episodes:
  desc: null
  value: 200
observation_builder:
  desc: null
  value: GraphObsForRailEnv
observation_depth:
  desc: null
  value: 3
offset:
  desc: null
  value: 25
predictor:
  desc: null
  value: ShortestPathPredictorForRailEnv
render:
  desc: null
  value: false
resume_weights:
  desc: null
  value: true
reward_scaling:
  desc: null
  value: 0.1
run_title:
  desc: null
  value: first_run
save_model_interval:
  desc: null
  value: 50
seed:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 0
start_lr_decay:
  desc: null
  value: 150
use_stop_action:
  desc: null
  value: false
view_height:
  desc: null
  value: 30
view_semiwidth:
  desc: null
  value: 7
wandb_project_name:
  desc: null
  value: wandb_default
width:
  desc: null
  value: 25
